name: Build code, run unit test, run SAST, SCA, DAST security scans
on: workflow_dispatch

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./

  sonarcloud-sast-scan:
    runs-on: ubuntu-latest
    name: SonarCloud SAST scan
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=githubactionsdevsecops -Dsonar.organization=githubactionsdevsecops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
