name: Horusec SAST scan
on: workflow_dispatch
permissions: 
  contents: read
  issues: write

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ -e="false" -w="true" -j="true" -o="json" -O="./output.json"
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: ./output.json
        
      #- name: Download a single artifact
       # uses: actions/download-artifact@v3
        #with:
         # name: horusec-report
         
      - uses: actions/checkout@v2
      - name: Read/Write data into README
        uses: eddiejaoude/github-actions-reader-writer@v0.1
        with:
          json-file-path: 'output.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #columns: 3
          object-field-names: '[ "githubUsername", "name", "imageUrl", "issueNumber" ]'
          file-to-use: 'README.md'
          html-cell: '<td align="center"><p><a href="https://github.com/{{ githubUsername }}">{{ name }}</a></p><img src="{{ imageUrl }}" /><p><a href="https://github.com/EddieJaoudeCommunity/awesome-github-profiles/issues/{{ issueNumber }}">(:100: give your vote)</a></p></td>'
      
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          filename: ${{ steps.table.outputs.table }}
  
