name: Horusec SAST scan
on: workflow_dispatch
permissions: 
  contents: read
  issues: write

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ -e="false" -w="true" -j="true" -o="json" -O="./output.json"
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: ./output.json
          retention-days: 5

  download-artifacts-e-create-issue:
    runs-on: ubuntu-latest
    needs: horusec-sast-scan  #wait for the artifacts
    name: download-artifacts-e-create-issue
    steps:
      - uses: actions/checkout@v3

      - name: Download the artifact
        uses: actions/download-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: horusec-report
          
      - name: Print the json result
        shell: bash
        run: |
          value=`cat ./output.json`
          echo The result is $value

      #- name: Rename file .json to .md e print it
      #  run: |
      #    mv ./output.json ./output.md
      #    ls
      #    value=`cat ./output.md`
      #    echo The result is $value

      #- name: Delete file 
      #  run: rm -f file.txt

      
      - name: npm install
        run: npm install
      - name: Generate linting report
        run: npm run lint:js -- --output-file eslint-report.json --format json
        continue-on-error: true
      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint-report.json'
      - name: Update summary
        run: |
          npm_config_yes=true npx github:10up/eslint-json-to-md --path ./output.json --output ./output.md
          cat output.md >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}

      #FUNZIONA
      - name: Create Issue From File
        id: horusec-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Horusec output 
          content-filepath: ./output.md
          labels: |
            report
            automated issue
    

    
  
