name: Horusec SAST scan
on: workflow_dispatch
permissions: 
  contents: read
  issues: write

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ -e="false" -w="true" -j="true" -o="json" -O="./output.json"
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: ./output.json
          retention-days: 5

  download-artifacts-e-create-issue:
    runs-on: ubuntu-latest
    needs: horusec-sast-scan  #wait for the artifacts
    name: download-artifacts-e-create-issue
    steps:
      - uses: actions/checkout@v3

      - name: Download the artifact
        uses: actions/download-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: horusec-report
          
      - name: Print the final result
        shell: bash
        run: |
          value=`cat ./output.json`
          echo The result is $value

      - name: Rename file 
        run: mv ./output.json ./output.md

      #- name: Delete file 
      #  run: rm -f file.txt
          
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./output.md
    

    
  
