name: Horusec SAST scan
on: workflow_dispatch
permissions: 
  contents: read
  issues: write

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ -e="false" -w="true" -j="true" -o="json" -O="horusec-output.json"
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: horusec-output.json
          retention-days: 5

  download-artifacts-e-create-issue:
    runs-on: ubuntu-latest
    needs: horusec-sast-scan  #wait for the artifacts
    name: download-artifacts-e-create-issue
    steps:
      - uses: actions/checkout@v3

      - name: Download the artifact
        uses: actions/download-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: horusec-report
          
      - name: Print the json result
        id: stampalog
        shell: bash
        run: |
          value=`cat horusec-output.json`
          echo The result is $value

      #- name: Set Json as EV
      #  run: |
      #    JSON_CONTENT=$(cat horusec-output.json)
      #    echo "JSON_CONTENT=$JSON_CONTENT" >> $GITHUB_ENV

      - name: Convert Json to md
        uses: buildingcash/json-to-markdown-table-action@v1
        with:
          json: $(cat horusec-output.json)

      #- name: Rename file .json to .md e print it
      #  run: |
      #    mv ./output.json ./output.md
      #    ls
      #    value=`cat ./output.md`
      #    echo The result is $value

      #- name: Delete file 
      #  run: rm -f file.txt

      #- name: stampa json
      #  run: echo "${{ steps.stampalog.outputs }}"

      #Test Json to table md
      #- uses: buildingcash/json-to-markdown-table-action@v1
      #  id: table
      #  with:
      #    json: ${{ steps.stampalog.outputs }}
      #- run: echo ${{ steps.table.outputs.table }}

      - name: Create Issue From File
        id: horusec-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Horusec output 
          content-filepath: horusec-output.json
          labels: |
            report
            automated issue
    

    
  
