name: Horusec SAST scan
on: workflow_dispatch
permissions: 
  contents: read
  issues: write

jobs:
  horusec-sast-scan:
    runs-on: ubuntu-latest
    name: Horusec SAST scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ -e="false" -w="true" -j="true" -o="json" -O="./output.json"
            
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: horusec-report
          path: ./output.json

      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Horusec issue
          body: output.json
      - run: |
          echo "${{ steps.new-issue.outputs.number }}"
          echo "${{ steps.new-issue.outputs.html_url }}"
          echo '${{ steps.new-issue.outputs.json }}' | jq 
          echo '${{ steps.new-issue.outputs.json }}' | jq .state
          echo '${{ steps.new-issue.outputs.json }}' | jq .labels[].name
          echo output.json
        
      #- name: Download a single artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #   name: horusec-report
              
      #- name: create an issue
      #  uses: JasonEtco/create-an-issue@v2
      #  env:
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #  with:
      #    filename: $output.json
  
