name: Sonarcloud SAST scan
on: workflow_dispatch

jobs:
  sonarcloud-sast-scan:
      runs-on: ubuntu-latest
      name: SonarCloud SAST scan
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  #prevent shallow clones
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          fetch-depth: 0
          cache: maven
      - name: Build with Maven cloud
        run: >
          mvn -B verify 
          sonar:sonar 
          -Dsonar.projectKey=devsecops-playground_playground 
          -Dsonar.organization=devsecops-playground 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.token=$SONAR_TOKEN        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
