name: run with teller
on: workflow_dispatch

jobs:
  build:
    name: Build your code
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master


      # set up teller
      - name: Setup Teller
        uses: tellerops/teller@v1

      - name: Run a Teller task (show, scan, run, etc.)
        run: teller run [args]
