name: Teller Secret Scan
on:
  workflow_dispatch

jobs:
  build:
    name: Build your code
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main


      # set up teller
      - name: Setup Teller
        uses: spectralops/setup-teller-action@v2

      - name: Run a Teller task (show, scan, run, etc.)
        run: teller show 
