name: Build code, run unit test, run SAST, SCA, DAST security scans
on: workflow_dispatch

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest
    name: ZAP DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
